---

- name: Add Docker repository key
  become: yes
  apt_key:
    id: "{{ apt_key_sig }}"
    url: "{{ apt_key_url }}"
    state: present

- name: Add Docker repository and update apt cache
  become: yes
  apt_repository:
    repo: "{{ apt_repository }}"
    update_cache: yes
    state: present

- name: Install (or update) docker and python packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - "{{ docker_package }}"
    - python-dev
    - python-pip

- name: Upgrade latest pip, setuptools and docker-py with pip
  become: yes
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - setuptools
    - docker-py

- name: Set docker daemon options
  become: yes
  lineinfile:
    dest: "{{ docker_config_file }}"
    create: yes
    line: "DOCKER_OPTS=\"{{ docker_opts.rstrip('\n') }}\""
    state: present
  notify:
    - Restart docker
  when: docker_opts != ""

- name: Set custom tmp dir for Docker
  become: yes
  lineinfile:
    dest: "{{ docker_config_file }}"
    create: yes
    line: "export DOCKER_TMPDIR={{ docker_tmpdir }}"
    state: present
  notify:
    - Restart docker
  when: docker_tmpdir != ""

- name: Create a group for docker_user
  group:
    name: "{{ docker_group }}"
    state: present
  when: docker_user != "" and docker_group != ""

- name: Let a user run docker without sudo
  become: yes
  user:
    name: "{{ docker_user }}"
    groups: "{{ docker_group }}"
    append: yes
    state: present
  when: docker_user != ""

- name: Start docker
  become: yes
  service:
    name: docker
    state: started
